import type { Category, CategorySlug } from "./types";

export const CATEGORIES: Category[] = [
  {
    slug: "ai-models",
    name: "AI / Models",
    description: "LLM releases, benchmarks, and model updates",
    icon: "Brain",
    colorAccent: "#7c3aed",
    colorBg: "#1a0533",
    colorLabel: "#c4b5fd",
    storyCount: 47,
    lastUpdated: "14m ago",
  },
  {
    slug: "startups",
    name: "Startups",
    description: "New companies, launches, and pivots",
    icon: "Rocket",
    colorAccent: "#16a34a",
    colorBg: "#0a2015",
    colorLabel: "#4ade80",
    storyCount: 23,
    lastUpdated: "41m ago",
  },
  {
    slug: "big-tech",
    name: "Big Tech",
    description: "FAANG and enterprise AI moves",
    icon: "Building2",
    colorAccent: "#4f46e5",
    colorBg: "#0f0f2d",
    colorLabel: "#818cf8",
    storyCount: 31,
    lastUpdated: "1h ago",
  },
  {
    slug: "research",
    name: "Research",
    description: "Papers, findings, and academic breakthroughs",
    icon: "FlaskConical",
    colorAccent: "#0891b2",
    colorBg: "#001f2e",
    colorLabel: "#22d3ee",
    storyCount: 18,
    lastUpdated: "2h ago",
  },
  {
    slug: "tools",
    name: "Tools",
    description: "Developer tools, APIs, and integrations",
    icon: "Wrench",
    colorAccent: "#2563eb",
    colorBg: "#0d1f3c",
    colorLabel: "#60a5fa",
    storyCount: 29,
    lastUpdated: "55m ago",
  },
  {
    slug: "open-source",
    name: "Open Source",
    description: "Repos, releases, and community projects",
    icon: "Code2",
    colorAccent: "#ea580c",
    colorBg: "#2d1100",
    colorLabel: "#fb923c",
    storyCount: 14,
    lastUpdated: "3h ago",
  },
  {
    slug: "funding",
    name: "Funding",
    description: "Rounds, acquisitions, and valuations",
    icon: "DollarSign",
    colorAccent: "#d97706",
    colorBg: "#2d1a00",
    colorLabel: "#fbbf24",
    storyCount: 9,
    lastUpdated: "5h ago",
  },
  {
    slug: "producthunt",
    name: "Product Hunt",
    description: "Top AI product launches from Product Hunt",
    icon: "Zap",
    colorAccent: "#FF6154",
    colorBg: "#2d0e0b",
    colorLabel: "#ff9e97",
  },
];

export const CATEGORY_TABS: { slug: CategorySlug; label: string }[] = [
  { slug: "all", label: "All" },
  { slug: "ai-models", label: "AI" },
  { slug: "tools", label: "Tools" },
  { slug: "startups", label: "Startups" },
  { slug: "open-source", label: "Open Source" },
  { slug: "research", label: "Research" },
  { slug: "funding", label: "Funding" },
  { slug: "big-tech", label: "Big Tech" },
  { slug: "producthunt", label: "Product Hunt" },
];

export function getCategoryBySlug(slug: CategorySlug): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}
